- hosts: all
  become: true
  tasks: 
     - name: delete old deployment
       command: kubectl delete -f /home/alex/Deployment.yaml
     - name: delete old service
       command: kubectl delete -f /home/alex/service.yaml
     - name: create new deployment
       command: kubectl apply -f /home/alex/Deployment.yaml
     - name: create new service
       command: kubectl apply -f /home/alex/service.yaml
